[package]
name = "erg"
version = "0.4.5"
description = "The Erg programming language"
authors = ["Shunsuke Shibayama <sbym1346@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/erg-lang/erg"
documentation = "https://docs.rs/erg"
homepage = "https://erg-lang.github.io/"
keywords = ["erg", "programming-language"]

[workspace]
members = [
    "compiler/erg_common",
    "compiler/erg_compiler",
    "compiler/erg_parser",
    "compiler/erg_type",
]

[features]
# when "debug" feature is turned on, that of the following crates will also be turned on.
debug = [
    "erg_common/debug",
    "erg_parser/debug",
    "erg_compiler/debug",
    "erg_type/debug",
]
japanese = [
    "erg_common/japanese",
    "erg_parser/japanese",
    "erg_compiler/japanese",
    "erg_type/japanese",
]
simplified_chinese = [
    "erg_common/simplified_chinese",
    "erg_parser/simplified_chinese",
    "erg_compiler/simplified_chinese",
    "erg_type/simplified_chinese",
]
traditional_chinese = [
    "erg_common/traditional_chinese",
    "erg_parser/traditional_chinese",
    "erg_compiler/traditional_chinese",
    "erg_type/traditional_chinese",
]

[dependencies]
erg_common = { version = "0.4.5", path = "./compiler/erg_common" }
erg_parser = { version = "0.4.5", path = "./compiler/erg_parser" }
erg_compiler = { version = "0.4.5", path = "./compiler/erg_compiler" }
erg_type = { version = "0.4.5", path = "./compiler/erg_type" }

# [workspace]
# member = ["cm", "dyne"]

# [profile.release]
# panic = 'abort'

# [[bin]]
# name = "cm"
# path = "src/compiler/main.rs"
