[package]
name = "erg_parser"
version = "0.5.7-nightly.2"
description = "The Erg parser"
authors = ["erg-lang team <moderation.erglang@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/erg-lang/erg/tree/main/src/erg_compiler/erg_parser"
documentation = "https://docs.rs/erg_parser"
homepage = "https://erg-lang.github.io/"

[features]
debug = [ "erg_common/debug" ]
japanese = [ "erg_common/japanese" ]
simplified_chinese = [ "erg_common/simplified_chinese" ]
traditional_chinese = [ "erg_common/traditional_chinese" ]

[dependencies]
erg_common = { version = "0.5.7-nightly.2", path = "../erg_common" }

[lib]
path = "lib.rs"

[[bin]]
name = "ergp"
path = "main.rs"
