[alias]
lex = "run -- --mode lex"
prs = "run -- --mode parse"
lwr = "run -- --mode lower"
chk = "run -- --mode check"
cmp = "run -- --mode compile"
trans = "run -- --mode transpile"
ex = "run -- --mode exec"
read = "run -- --mode read"

dlex = "run --features debug -- --mode lex"
dprs = "run --features debug -- --mode parse"
dlwr = "run --features debug -- --mode lower"
dchk = "run --features debug -- --mode check"
dcmp = "run --features debug -- --mode compile"
dtrans = "run --features debug -- --mode transpile"
dex = "run --features debug -- --mode exec"
dread = "run --features debug -- --mode read"

inst = "install --path . --features els"
dinst = "install --path . --features debug --features els"
