name: Docs

on:
  push:
    branches: [main]
    paths:
      - "doc/**"

jobs:
  update-summary:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          python sync_to_summary.py
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Automatic update \`SUMMARY.md\`"
          git push
