name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: |
        rustup update stable
        cargo build --verbose
    # Removed because it caused a segmentation fault and would not stop executing. Testing should be done locally.
    # - name: Run tests
    #   run: cargo test --verbose -- --test-threads=2
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
